"""seed_data.py — 실제 데이터 기반 (친구 조사 단가표 + 트렌드 반영)"""

PRICE_TABLE = {
    "피스타치오": {"unit_amount": 1000, "unit_price": 30000},
    "카다이프": {"unit_amount": 500, "unit_price": 6500},
    "다크초콜릿": {"unit_amount": 1000, "unit_price": 20000},
    "코코아파우더": {"unit_amount": 1000, "unit_price": 15000},
    "타히니": {"unit_amount": 1000, "unit_price": 15000},
    "마시멜로": {"unit_amount": 1000, "unit_price": 8500},
    "찹쌀가루": {"unit_amount": 1000, "unit_price": 4000},
    "타피오카전분": {"unit_amount": 1000, "unit_price": 4500},
    "버터": {"unit_amount": 450, "unit_price": 8500},
    "크림치즈": {"unit_amount": 1000, "unit_price": 15000},
    "마스카포네치즈": {"unit_amount": 500, "unit_price": 10000},
    "말차파우더": {"unit_amount": 500, "unit_price": 30000},
    "그릭요거트": {"unit_amount": 1000, "unit_price": 11500},
    "그래놀라": {"unit_amount": 1000, "unit_price": 11500},
    "단백질파우더": {"unit_amount": 1000, "unit_price": 30000},
    "생크림": {"unit_amount": 1000, "unit_price": 7500},
    "딸기": {"unit_amount": 1000, "unit_price": 14000},
    "망고냉동": {"unit_amount": 1000, "unit_price": 8000},
    "복숭아냉동": {"unit_amount": 1000, "unit_price": 8000},
    "와플믹스": {"unit_amount": 1000, "unit_price": 6000},
    "설탕": {"unit_amount": 1000, "unit_price": 2250},
    "코코넛워터": {"unit_amount": 1000, "unit_price": 3000},
    "오렌지농축액": {"unit_amount": 1000, "unit_price": 6000},
    "에스프레소원두": {"unit_amount": 1000, "unit_price": 22500},
    "라이스페이퍼": {"unit_amount": 400, "unit_price": 3000},
    "바닐라페이스트": {"unit_amount": 100, "unit_price": 20000},
    "우베파우더": {"unit_amount": 1000, "unit_price": 22500},
    "크루아상": {"unit_amount": 1, "unit_price": 458},
    "우유": {"unit_amount": 1000, "unit_price": 1200},
    "밀가루": {"unit_amount": 1000, "unit_price": 1500},
    "달걀": {"unit_amount": 1, "unit_price": 300},
}

TRENDS = [
    {"name": "두바이 초콜릿", "ingredients": ["피스타치오", "카다이프", "다크초콜릿", "타히니"], "tag": "#두바이초콜릿"},
    {"name": "두쫀쿠", "ingredients": ["피스타치오", "카다이프", "마시멜로"], "tag": "#두쫀쿠"},
    {"name": "카눌레", "ingredients": ["밀가루", "우유", "달걀", "바닐라페이스트"], "tag": "#카눌레"},
    {"name": "상하이버터떡", "ingredients": ["찹쌀가루", "타피오카전분", "버터"], "tag": "#상하이버터떡"},
    {"name": "모찌도넛", "ingredients": ["찹쌀가루", "밀가루"], "tag": "#모찌도넛"},
    {"name": "말차 디저트", "ingredients": ["말차파우더", "우유", "생크림"], "tag": "#말차디저트"},
    {"name": "우베 디저트", "ingredients": ["우베파우더", "우유", "생크림"], "tag": "#우베"},
    {"name": "그릭요거트볼", "ingredients": ["그릭요거트", "딸기", "그래놀라"], "tag": "#그릭요거트볼"},
    {"name": "프로틴 브라우니", "ingredients": ["단백질파우더", "코코아파우더"], "tag": "#프로틴브라우니"},
    {"name": "프로틴 치즈케이크", "ingredients": ["크림치즈", "단백질파우더"], "tag": "#프로틴치즈케이크"},
    {"name": "미니 티라미수", "ingredients": ["마스카포네치즈", "에스프레소원두"], "tag": "#미니티라미수"},
    {"name": "미니 치즈케이크", "ingredients": ["크림치즈"], "tag": "#미니치즈케이크"},
    {"name": "도트케이크", "ingredients": ["생크림"], "tag": "#도트케이크"},
    {"name": "과일 무스케이크", "ingredients": ["망고냉동", "딸기", "복숭아냉동", "생크림"], "tag": "#과일무스"},
    {"name": "크로플", "ingredients": ["크루아상", "와플믹스"], "tag": "#크로플"},
    {"name": "탕후루", "ingredients": ["딸기", "설탕"], "tag": "#탕후루"},
    {"name": "크룽지", "ingredients": ["크루아상", "설탕", "버터"], "tag": "#크룽지"},
    {"name": "코코넛 아메리카노", "ingredients": ["코코넛워터", "에스프레소원두"], "tag": "#코코넛아메리카노"},
    {"name": "오렌지 아메리카노", "ingredients": ["오렌지농축액", "에스프레소원두"], "tag": "#오렌지아메리카노"},
    {"name": "라이스페이퍼 모찌", "ingredients": ["라이스페이퍼", "그릭요거트", "딸기"], "tag": "#라이스페이퍼모찌"},
]

RECIPES = [
    {"situation": "보유 재고: 크루아상·버터, 트렌드: 두바이 초콜릿", "menu": "두바이풍 피스타치오 크룽지",
     "recipe": [{"name": "크루아상", "amount": 1, "from_stock": True}, {"name": "버터", "amount": 15, "from_stock": True},
                {"name": "피스타치오", "amount": 15, "from_stock": False}, {"name": "카다이프", "amount": 15, "from_stock": False}],
     "price": 5800},
    {"situation": "보유 재고: 마시멜로, 트렌드: 두쫀쿠", "menu": "두쫀쿠 (두바이 쫀득 쿠키)",
     "recipe": [{"name": "밀가루", "amount": 50, "from_stock": False}, {"name": "피스타치오", "amount": 15, "from_stock": False},
                {"name": "카다이프", "amount": 15, "from_stock": False}, {"name": "마시멜로", "amount": 15, "from_stock": True}],
     "price": 4500},
    {"situation": "보유 재고: 우유·달걀, 트렌드: 카눌레", "menu": "바닐라 카눌레",
     "recipe": [{"name": "밀가루", "amount": 30, "from_stock": False}, {"name": "우유", "amount": 100, "from_stock": True},
                {"name": "달걀", "amount": 1, "from_stock": True}, {"name": "바닐라페이스트", "amount": 2, "from_stock": False}],
     "price": 4000},
    {"situation": "보유 재고: 버터, 트렌드: 상하이버터떡", "menu": "상하이 버터떡",
     "recipe": [{"name": "찹쌀가루", "amount": 50, "from_stock": False}, {"name": "타피오카전분", "amount": 20, "from_stock": False},
                {"name": "버터", "amount": 20, "from_stock": True}],
     "price": 3500},
    {"situation": "보유 재고: 없음, 트렌드: 모찌도넛", "menu": "모찌 도넛",
     "recipe": [{"name": "찹쌀가루", "amount": 40, "from_stock": False}, {"name": "밀가루", "amount": 30, "from_stock": False},
                {"name": "설탕", "amount": 10, "from_stock": False}],
     "price": 3000},
    {"situation": "보유 재고: 우유·생크림, 트렌드: 말차 디저트", "menu": "말차 크림 라떼",
     "recipe": [{"name": "말차파우더", "amount": 4, "from_stock": False}, {"name": "우유", "amount": 200, "from_stock": True},
                {"name": "생크림", "amount": 50, "from_stock": True}],
     "price": 6000},
    {"situation": "보유 재고: 우유·생크림, 트렌드: 우베 디저트", "menu": "우베 크림 라떼",
     "recipe": [{"name": "우베파우더", "amount": 5, "from_stock": False}, {"name": "우유", "amount": 200, "from_stock": True},
                {"name": "생크림", "amount": 50, "from_stock": True}],
     "price": 6000},
    {"situation": "보유 재고: 그릭요거트, 트렌드: 그릭요거트볼", "menu": "딸기 그릭요거트볼",
     "recipe": [{"name": "그릭요거트", "amount": 120, "from_stock": True}, {"name": "딸기", "amount": 50, "from_stock": False},
                {"name": "그래놀라", "amount": 30, "from_stock": False}],
     "price": 6500},
    {"situation": "보유 재고: 없음, 트렌드: 프로틴 브라우니", "menu": "프로틴 브라우니",
     "recipe": [{"name": "단백질파우더", "amount": 30, "from_stock": False}, {"name": "코코아파우더", "amount": 15, "from_stock": False},
                {"name": "달걀", "amount": 1, "from_stock": False}],
     "price": 5000},
    {"situation": "보유 재고: 크림치즈, 트렌드: 프로틴 치즈케이크", "menu": "프로틴 치즈케이크",
     "recipe": [{"name": "크림치즈", "amount": 80, "from_stock": True}, {"name": "단백질파우더", "amount": 20, "from_stock": False}],
     "price": 6500},
    {"situation": "보유 재고: 에스프레소, 트렌드: 미니 티라미수", "menu": "미니 티라미수",
     "recipe": [{"name": "마스카포네치즈", "amount": 60, "from_stock": False}, {"name": "에스프레소원두", "amount": 18, "from_stock": True}],
     "price": 6000},
    {"situation": "보유 재고: 크림치즈, 트렌드: 미니 치즈케이크", "menu": "미니 치즈케이크",
     "recipe": [{"name": "크림치즈", "amount": 70, "from_stock": True}, {"name": "설탕", "amount": 15, "from_stock": False}],
     "price": 5000},
    {"situation": "보유 재고: 생크림, 트렌드: 도트케이크", "menu": "도트 생크림 케이크",
     "recipe": [{"name": "생크림", "amount": 80, "from_stock": True}, {"name": "밀가루", "amount": 40, "from_stock": False},
                {"name": "설탕", "amount": 15, "from_stock": False}],
     "price": 5500},
    {"situation": "보유 재고: 생크림, 트렌드: 과일 무스케이크", "menu": "과일 무스케이크",
     "recipe": [{"name": "망고냉동", "amount": 40, "from_stock": False}, {"name": "딸기", "amount": 40, "from_stock": False},
                {"name": "생크림", "amount": 80, "from_stock": True}],
     "price": 6500},
    {"situation": "보유 재고: 크루아상, 트렌드: 크로플", "menu": "크로플",
     "recipe": [{"name": "크루아상", "amount": 1, "from_stock": True}, {"name": "와플믹스", "amount": 20, "from_stock": False}],
     "price": 4000},
    {"situation": "보유 재고: 없음, 트렌드: 탕후루", "menu": "딸기 탕후루",
     "recipe": [{"name": "딸기", "amount": 60, "from_stock": False}, {"name": "설탕", "amount": 30, "from_stock": False}],
     "price": 3500},
    {"situation": "보유 재고: 크루아상, 트렌드: 크룽지", "menu": "버터 크룽지",
     "recipe": [{"name": "크루아상", "amount": 1, "from_stock": True}, {"name": "버터", "amount": 15, "from_stock": False},
                {"name": "설탕", "amount": 8, "from_stock": False}],
     "price": 3800},
    {"situation": "보유 재고: 에스프레소, 트렌드: 코코넛 아메리카노", "menu": "코코넛 아메리카노",
     "recipe": [{"name": "코코넛워터", "amount": 150, "from_stock": False}, {"name": "에스프레소원두", "amount": 18, "from_stock": True}],
     "price": 5000},
    {"situation": "보유 재고: 에스프레소, 트렌드: 오렌지 아메리카노", "menu": "오렌지 아메리카노",
     "recipe": [{"name": "오렌지농축액", "amount": 30, "from_stock": False}, {"name": "에스프레소원두", "amount": 18, "from_stock": True}],
     "price": 5000},
    {"situation": "보유 재고: 그릭요거트, 트렌드: 라이스페이퍼 모찌", "menu": "라이스페이퍼 과일 모찌",
     "recipe": [{"name": "라이스페이퍼", "amount": 20, "from_stock": False}, {"name": "그릭요거트", "amount": 60, "from_stock": True},
                {"name": "딸기", "amount": 30, "from_stock": False}],
     "price": 4500},
]